Attribute VB_Name = "Declar"
'*******************************************************************************
'*
'* $Source: $
'*
'* Author:          Michael Schneider, LCoE
'*
'* Function:        Global module for definition of variables
'*
'* Functional Area: ELA
'*
'* $Revision: $
'* $Date: $
'*
'* $Log: $
'*
'* $NoKeywords: $
'*******************************************************************************

'**************************************************************
' Declaration of public variables
'**************************************************************

' Name of DLL
Public gsModuleName As String

' Variables for saving content of password form
Public gsFieldText As String

' Variables for saving content of password form
Public gsFieldLabel As String

' Type de selection de l'opérateur
Public Is_ok As Integer

Public gSystemOCX   As Object
Public gRDOConn     As rdoConnection

Sub Main()

End Sub


