create or replace view BALI_PRINTERY_MODULE  as
SELECT
  GWUSERATTRIBUTEST.username			   username,
  GWMENUITEMINFOT.eventname				   eventname,
  GWMENUTEMPLATEST.templatename			   template
FROM
  GWUSERATTRIBUTEST,
  GWMENUTEMPLATEST,
  GWMENUITEMINFOT
WHERE
  GWUSERATTRIBUTEST.menutemplatename = GWMENUTEMPLATEST.templatename  and
  GWMENUTEMPLATEST.templateid = GWMENUITEMINFOT.templateid ;

CREATE PUBLIC SYNONYM BALI_PRINTERY_MODULE FOR BALI_PRINTERY_MODULE ;
GRANT SELECT ON BALI_PRINTERY_MODULE TO PUBLIC ;


